Location:
    -
        Name: Route 13-14 Entrance
        FileName: Route14.asm
        Type: Map
        HasPKMN: No
        WildTableList: 
        LocationReqs:
            - Route 15 Entrance
        FlagReqs:
        ItemReqs:
        FlagsSet:
        ReachableReqs:
        Code:
        Text:
        TrainerList: 
        Sublocations:
    -
        Name: Route 13-14 Entrance
        FileName: Route14.asm
        Type: Map
        HasPKMN: Yes
        WildTableList: 
        LocationReqs:
            - Route 12
        FlagReqs:
        ItemReqs:
        FlagsSet:
        ReachableReqs:
        Code:
        Text:
        TrainerList: 
        Sublocations:
    -
        Name: Route 13 and 14
        FileName: Route14.asm
        Type: Map
        HasPKMN: Yes
        WildTableList: 
            - ROUTE 13
            - ROUTE 14
        LocationReqs:
            - Route 13-14 Entrance
        FlagReqs:
        ItemReqs:
        FlagsSet:
        ReachableReqs:
        Code:
        Text:
        AREALV: 32
        TrainerList:
            - BIRD_KEEPER 9
            - POKEFANM 5
            - POKEFANM 6
            - BIRD_KEEPER 16
            - BIRD_KEEPER 15
            - POKEFANM 4
            - POKEFANM 12
            - HIKER 16
        Sublocations:
            -
                Name: Route 13 Hidden Calcium
                FileName: Route13.asm
                SecondaryFile: Route13.asm
                Type: Item
                HasPKMN: No
                WildTableList:
                LocationReqs: Route 13 and 14
                FlagReqs:
                    - Hidden Items
                ItemReqs:
                FlagsSet:
                ReachableReqs:
                NormalItem: CALCIUM
                Code: |
                    Route13HiddenCalcium:
                        ITEMLINE
                SecondaryCode: '    bg_event 30, 13, BGEVENT_ITEM, Route13HiddenCalcium'
                Text:
                TrainerList: 
                Sublocations: